// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKGPS4WTthdFKxBnPLoUYoLJRx615DbM',
    appId: '1:401414505424:web:1622d561cca87167302fd5',
    messagingSenderId: '401414505424',
    projectId: 'swiftshopperappv2',
    authDomain: 'swiftshopperappv2.firebaseapp.com',
    storageBucket: 'swiftshopperappv2.firebasestorage.app',
    measurementId: 'G-QSDLPD8KBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRsrRHf_YphPYWCAqdgbN3RYE1XBEAljs',
    appId: '1:401414505424:android:13da6aa4de36eb7b302fd5',
    messagingSenderId: '401414505424',
    projectId: 'swiftshopperappv2',
    storageBucket: 'swiftshopperappv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoDUW01pwWGrbloL_J_0LhdYTMOfzXulE',
    appId: '1:401414505424:ios:adfc6e294d71f8ef302fd5',
    messagingSenderId: '401414505424',
    projectId: 'swiftshopperappv2',
    storageBucket: 'swiftshopperappv2.firebasestorage.app',
    iosBundleId: 'com.example.swiftshopper2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoDUW01pwWGrbloL_J_0LhdYTMOfzXulE',
    appId: '1:401414505424:ios:adfc6e294d71f8ef302fd5',
    messagingSenderId: '401414505424',
    projectId: 'swiftshopperappv2',
    storageBucket: 'swiftshopperappv2.firebasestorage.app',
    iosBundleId: 'com.example.swiftshopper2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKKGPS4WTthdFKxBnPLoUYoLJRx615DbM',
    appId: '1:401414505424:web:ac63716c67ee9fe3302fd5',
    messagingSenderId: '401414505424',
    projectId: 'swiftshopperappv2',
    authDomain: 'swiftshopperappv2.firebaseapp.com',
    storageBucket: 'swiftshopperappv2.firebasestorage.app',
    measurementId: 'G-TF23D4KMMQ',
  );
}
